version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t shiv-ecr-repo:latest .
      - docker tag shiv-ecr-repo:latest 315438239075.dkr.ecr.us-east-1.amazonaws.com/shiv-ecr-repo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
  
